site_name: Math Problems Solutions
site_url: https://liiiinadnamar.github.io/Math_Problems_Repo_DR/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Home: 'index.md'
  - 'Lecture: Probabilistic Methods':
    - Basic:
      - '1. Events & Probability — Solutions': '4_Metody_probabilistyczne/basic/solution_01_events_and_probability.md'
